import type { Product, ProductImage } from '@prisma/client';
type ProductWithImages = Product & {
    images?: ProductImage[];
};
export declare function toDealerInventoryDto(product: ProductWithImages): {
    id: string;
    company_id: string;
    slug: string;
    make: string;
    model: string;
    trim: string | null;
    model_year: number;
    condition: import(".prisma/client").$Enums.VehicleCondition;
    engine: string | null;
    transmission: import(".prisma/client").$Enums.Transmission | null;
    cylinders: number | null;
    drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
    body_type: import(".prisma/client").$Enums.BodyType | null;
    warranty_months: number | null;
    warranty_notes: string | null;
    color: string | null;
    mileage: number | null;
    vin: string | null;
    chassis_number: string | null;
    engine_number: string | null;
    identity_complete: boolean;
    description: string | null;
    price: number;
    finance_eligible: boolean;
    default_offer_id: string | null;
    listing_status: import(".prisma/client").$Enums.ListingStatus;
    published_at: Date | null;
    created_at: Date;
    updated_at: Date;
    primary_image: string | null;
    images: {
        id: string;
        storage_path: string;
        sort_order: number;
        alt_text: string | null;
    }[];
};
export declare function toDealerProductImageDto(image: ProductImage): {
    id: string;
    storage_path: string;
    sort_order: number;
    alt_text: string | null;
};
export declare function toDealerInventoryListResponse(items: ProductWithImages[], total: number, limit: number, offset: number): {
    total: number;
    limit: number;
    offset: number;
    items: {
        id: string;
        company_id: string;
        slug: string;
        make: string;
        model: string;
        trim: string | null;
        model_year: number;
        condition: import(".prisma/client").$Enums.VehicleCondition;
        engine: string | null;
        transmission: import(".prisma/client").$Enums.Transmission | null;
        cylinders: number | null;
        drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
        body_type: import(".prisma/client").$Enums.BodyType | null;
        warranty_months: number | null;
        warranty_notes: string | null;
        color: string | null;
        mileage: number | null;
        vin: string | null;
        chassis_number: string | null;
        engine_number: string | null;
        identity_complete: boolean;
        description: string | null;
        price: number;
        finance_eligible: boolean;
        default_offer_id: string | null;
        listing_status: import(".prisma/client").$Enums.ListingStatus;
        published_at: Date | null;
        created_at: Date;
        updated_at: Date;
        primary_image: string | null;
        images: {
            id: string;
            storage_path: string;
            sort_order: number;
            alt_text: string | null;
        }[];
    }[];
};
export {};
