import { BodyType, Drivetrain, Prisma, Transmission, User, VehicleCondition } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { ActivityService } from '../common/activity.service';
import { PaginationQueryDto } from '../common/pagination.dto';
import { StorageService } from '../storage/storage.service';
import { type VehicleIdentityInput } from './vehicle-identity';
export type ProductInputDto = {
    companyId?: string;
    make: string;
    model: string;
    trim?: string;
    modelYear: number;
    condition?: VehicleCondition;
    engine?: string;
    transmission?: Transmission;
    cylinders?: number;
    drivetrain?: Drivetrain;
    bodyType?: BodyType;
    warrantyMonths?: number;
    warrantyNotes?: string;
    color?: string;
    mileage?: number;
    description?: string;
    price: number;
    financeEligible?: boolean;
    defaultOfferId?: string;
} & VehicleIdentityInput;
export declare class ProductsService {
    private readonly prisma;
    private readonly activity;
    private readonly storage;
    constructor(prisma: PrismaService, activity: ActivityService, storage: StorageService);
    listPublished(query: {
        make?: string;
        model?: string;
        yearMin?: number;
        yearMax?: number;
        priceMin?: number;
        priceMax?: number;
        condition?: VehicleCondition;
        companyId?: string;
        transmission?: Transmission;
        drivetrain?: Drivetrain;
        bodyType?: BodyType;
        cylinders?: number;
        mileageMax?: number;
        hasWarranty?: boolean;
        q?: string;
        limit?: number;
        offset?: number;
        sort?: 'newest' | 'price_asc' | 'price_desc' | 'year_desc' | 'mileage_asc';
    }): Promise<{
        total: number;
        limit: number;
        offset: number;
        items: {
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: import(".prisma/client").$Enums.VehicleCondition;
            transmission: import(".prisma/client").$Enums.Transmission | null;
            cylinders: number | null;
            drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
            body_type: import(".prisma/client").$Enums.BodyType | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number;
            finance_eligible: boolean;
            warranty_months: number | null;
            warranty_notes: string | null;
            attributes: Prisma.JsonArray;
            company_id: string;
            company_name: string;
            company_code: string | null;
            company_logo: string | null;
            primary_image: string;
            published_at: Date | null;
            est_monthly: number | null;
        }[];
    }>;
    private estimateMonthlyFromOffer;
    private static readonly FACET_ROW_CAP;
    listFacetOptions(): Promise<{
        makes: string[];
        models_by_make: Record<string, string[]>;
    }>;
    getBySlug(slug: string, viewer?: User | null): Promise<{
        available: boolean;
        availability: string;
        product: {
            engine: string | null;
            listing_status: import(".prisma/client").$Enums.ListingStatus;
            default_offer_id: string | null;
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: import(".prisma/client").$Enums.VehicleCondition;
            transmission: import(".prisma/client").$Enums.Transmission | null;
            cylinders: number | null;
            drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
            body_type: import(".prisma/client").$Enums.BodyType | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number;
            finance_eligible: boolean;
            warranty_months: number | null;
            warranty_notes: string | null;
            attributes: Prisma.JsonArray;
            company_id: string;
            company_name: string;
            company_code: string | null;
            company_logo: string | null;
            primary_image: string;
            published_at: Date | null;
            est_monthly: number | null;
        };
        images: {
            id: string;
            storage_path: string;
            sort_order: number;
            alt_text: string | null;
        }[];
        company: {
            id: string;
            name: string;
            code: string | null;
            logo_url: string | null;
            contact_phone: string | null;
        };
        offer: {
            id: string;
            name: string;
            annual_rent_rate: number;
            tenure_options: Prisma.JsonValue;
            min_down_payment_pct: number;
        } | null;
        reason?: undefined;
    } | {
        available: boolean;
        reason: string;
        availability?: undefined;
        product?: undefined;
        images?: undefined;
        company?: undefined;
        offer?: undefined;
    }>;
    listDealerInventory(user: User, query?: PaginationQueryDto): Promise<{
        total: number;
        limit: number;
        offset: number;
        items: {
            id: string;
            company_id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: import(".prisma/client").$Enums.VehicleCondition;
            engine: string | null;
            transmission: import(".prisma/client").$Enums.Transmission | null;
            cylinders: number | null;
            drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
            body_type: import(".prisma/client").$Enums.BodyType | null;
            warranty_months: number | null;
            warranty_notes: string | null;
            color: string | null;
            mileage: number | null;
            vin: string | null;
            chassis_number: string | null;
            engine_number: string | null;
            identity_complete: boolean;
            description: string | null;
            price: number;
            finance_eligible: boolean;
            default_offer_id: string | null;
            listing_status: import(".prisma/client").$Enums.ListingStatus;
            published_at: Date | null;
            created_at: Date;
            updated_at: Date;
            primary_image: string | null;
            images: {
                id: string;
                storage_path: string;
                sort_order: number;
                alt_text: string | null;
            }[];
        }[];
    }>;
    getDealerOne(user: User, id: string): Promise<{
        id: string;
        company_id: string;
        slug: string;
        make: string;
        model: string;
        trim: string | null;
        model_year: number;
        condition: import(".prisma/client").$Enums.VehicleCondition;
        engine: string | null;
        transmission: import(".prisma/client").$Enums.Transmission | null;
        cylinders: number | null;
        drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
        body_type: import(".prisma/client").$Enums.BodyType | null;
        warranty_months: number | null;
        warranty_notes: string | null;
        color: string | null;
        mileage: number | null;
        vin: string | null;
        chassis_number: string | null;
        engine_number: string | null;
        identity_complete: boolean;
        description: string | null;
        price: number;
        finance_eligible: boolean;
        default_offer_id: string | null;
        listing_status: import(".prisma/client").$Enums.ListingStatus;
        published_at: Date | null;
        created_at: Date;
        updated_at: Date;
        primary_image: string | null;
        images: {
            id: string;
            storage_path: string;
            sort_order: number;
            alt_text: string | null;
        }[];
    }>;
    create(user: User, dto: ProductInputDto): Promise<{
        id: string;
        company_id: string;
        slug: string;
        make: string;
        model: string;
        trim: string | null;
        model_year: number;
        condition: import(".prisma/client").$Enums.VehicleCondition;
        engine: string | null;
        transmission: import(".prisma/client").$Enums.Transmission | null;
        cylinders: number | null;
        drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
        body_type: import(".prisma/client").$Enums.BodyType | null;
        warranty_months: number | null;
        warranty_notes: string | null;
        color: string | null;
        mileage: number | null;
        vin: string | null;
        chassis_number: string | null;
        engine_number: string | null;
        identity_complete: boolean;
        description: string | null;
        price: number;
        finance_eligible: boolean;
        default_offer_id: string | null;
        listing_status: import(".prisma/client").$Enums.ListingStatus;
        published_at: Date | null;
        created_at: Date;
        updated_at: Date;
        primary_image: string | null;
        images: {
            id: string;
            storage_path: string;
            sort_order: number;
            alt_text: string | null;
        }[];
    }>;
    update(user: User, id: string, dto: Partial<ProductInputDto>): Promise<{
        id: string;
        company_id: string;
        slug: string;
        make: string;
        model: string;
        trim: string | null;
        model_year: number;
        condition: import(".prisma/client").$Enums.VehicleCondition;
        engine: string | null;
        transmission: import(".prisma/client").$Enums.Transmission | null;
        cylinders: number | null;
        drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
        body_type: import(".prisma/client").$Enums.BodyType | null;
        warranty_months: number | null;
        warranty_notes: string | null;
        color: string | null;
        mileage: number | null;
        vin: string | null;
        chassis_number: string | null;
        engine_number: string | null;
        identity_complete: boolean;
        description: string | null;
        price: number;
        finance_eligible: boolean;
        default_offer_id: string | null;
        listing_status: import(".prisma/client").$Enums.ListingStatus;
        published_at: Date | null;
        created_at: Date;
        updated_at: Date;
        primary_image: string | null;
        images: {
            id: string;
            storage_path: string;
            sort_order: number;
            alt_text: string | null;
        }[];
    }>;
    addImage(user: User, productId: string, file: Express.Multer.File): Promise<{
        id: string;
        storage_path: string;
        sort_order: number;
        alt_text: string | null;
    }>;
    publish(user: User, productId: string): Promise<{
        id: string;
        company_id: string;
        slug: string;
        make: string;
        model: string;
        trim: string | null;
        model_year: number;
        condition: import(".prisma/client").$Enums.VehicleCondition;
        engine: string | null;
        transmission: import(".prisma/client").$Enums.Transmission | null;
        cylinders: number | null;
        drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
        body_type: import(".prisma/client").$Enums.BodyType | null;
        warranty_months: number | null;
        warranty_notes: string | null;
        color: string | null;
        mileage: number | null;
        vin: string | null;
        chassis_number: string | null;
        engine_number: string | null;
        identity_complete: boolean;
        description: string | null;
        price: number;
        finance_eligible: boolean;
        default_offer_id: string | null;
        listing_status: import(".prisma/client").$Enums.ListingStatus;
        published_at: Date | null;
        created_at: Date;
        updated_at: Date;
        primary_image: string | null;
        images: {
            id: string;
            storage_path: string;
            sort_order: number;
            alt_text: string | null;
        }[];
    }>;
    unpublish(user: User, productId: string): Promise<{
        id: string;
        company_id: string;
        slug: string;
        make: string;
        model: string;
        trim: string | null;
        model_year: number;
        condition: import(".prisma/client").$Enums.VehicleCondition;
        engine: string | null;
        transmission: import(".prisma/client").$Enums.Transmission | null;
        cylinders: number | null;
        drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
        body_type: import(".prisma/client").$Enums.BodyType | null;
        warranty_months: number | null;
        warranty_notes: string | null;
        color: string | null;
        mileage: number | null;
        vin: string | null;
        chassis_number: string | null;
        engine_number: string | null;
        identity_complete: boolean;
        description: string | null;
        price: number;
        finance_eligible: boolean;
        default_offer_id: string | null;
        listing_status: import(".prisma/client").$Enums.ListingStatus;
        published_at: Date | null;
        created_at: Date;
        updated_at: Date;
        primary_image: string | null;
        images: {
            id: string;
            storage_path: string;
            sort_order: number;
            alt_text: string | null;
        }[];
    }>;
    buildSlug(dto: Pick<ProductInputDto, 'make' | 'model' | 'trim' | 'modelYear' | 'color' | 'transmission' | 'bodyType'>, id: string): string;
    getOpsOne(user: User, id: string): Promise<{
        company_name: string;
        company_code: string | null;
        default_offer_name: string | null;
        id: string;
        company_id: string;
        slug: string;
        make: string;
        model: string;
        trim: string | null;
        model_year: number;
        condition: import(".prisma/client").$Enums.VehicleCondition;
        engine: string | null;
        transmission: import(".prisma/client").$Enums.Transmission | null;
        cylinders: number | null;
        drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
        body_type: import(".prisma/client").$Enums.BodyType | null;
        warranty_months: number | null;
        warranty_notes: string | null;
        color: string | null;
        mileage: number | null;
        vin: string | null;
        chassis_number: string | null;
        engine_number: string | null;
        identity_complete: boolean;
        description: string | null;
        price: number;
        finance_eligible: boolean;
        default_offer_id: string | null;
        listing_status: import(".prisma/client").$Enums.ListingStatus;
        published_at: Date | null;
        created_at: Date;
        updated_at: Date;
        primary_image: string | null;
        images: {
            id: string;
            storage_path: string;
            sort_order: number;
            alt_text: string | null;
        }[];
    }>;
    updateOps(user: User, id: string, dto: Partial<ProductInputDto> & {
        listingStatus?: string;
    }): Promise<{
        id: string;
        company_id: string;
        slug: string;
        make: string;
        model: string;
        trim: string | null;
        model_year: number;
        condition: import(".prisma/client").$Enums.VehicleCondition;
        engine: string | null;
        transmission: import(".prisma/client").$Enums.Transmission | null;
        cylinders: number | null;
        drivetrain: import(".prisma/client").$Enums.Drivetrain | null;
        body_type: import(".prisma/client").$Enums.BodyType | null;
        warranty_months: number | null;
        warranty_notes: string | null;
        color: string | null;
        mileage: number | null;
        vin: string | null;
        chassis_number: string | null;
        engine_number: string | null;
        identity_complete: boolean;
        description: string | null;
        price: number;
        finance_eligible: boolean;
        default_offer_id: string | null;
        listing_status: import(".prisma/client").$Enums.ListingStatus;
        published_at: Date | null;
        created_at: Date;
        updated_at: Date;
        primary_image: string | null;
        images: {
            id: string;
            storage_path: string;
            sort_order: number;
            alt_text: string | null;
        }[];
    }>;
    deleteOps(user: User, id: string): Promise<{
        ok: boolean;
    }>;
    bulkStatus(user: User, ids: string[], listingStatus: string): Promise<{
        updated: number;
    }>;
    private requireDealerProduct;
    private toPublicCard;
    private toPublicDetail;
}
