import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { PaginationQueryDto } from '../common/pagination.dto';
export declare class CatalogService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    listPromotions(query: PaginationQueryDto): Promise<{
        total: number;
        limit: number;
        offset: number;
        items: unknown[];
    }>;
    getPromotion(id: string): Promise<{}>;
    createPromotion(data: Prisma.PromotionCreateInput): Prisma.Prisma__PromotionClient<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        description: string | null;
        startDate: Date | null;
        discountPercentage: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal | null;
        endDate: Date | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    updatePromotion(id: string, data: Prisma.PromotionUpdateInput): Prisma.Prisma__PromotionClient<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        description: string | null;
        startDate: Date | null;
        discountPercentage: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal | null;
        endDate: Date | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    deletePromotion(id: string): Prisma.Prisma__PromotionClient<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        description: string | null;
        startDate: Date | null;
        discountPercentage: Prisma.Decimal | null;
        discountAmount: Prisma.Decimal | null;
        endDate: Date | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    listInsurance(query: PaginationQueryDto): Promise<{
        total: number;
        limit: number;
        offset: number;
        items: unknown[];
    }>;
    getInsurance(id: string): Promise<{}>;
    createInsurance(data: Prisma.InsuranceRateCreateInput): Prisma.Prisma__InsuranceRateClient<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        description: string | null;
        isDefault: boolean;
        coverageType: string | null;
        annualRate: Prisma.Decimal;
        annualRateProvider: Prisma.Decimal;
        minVehicleValue: Prisma.Decimal | null;
        maxVehicleValue: Prisma.Decimal | null;
        minTenure: number | null;
        maxTenure: number | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    updateInsurance(id: string, data: Prisma.InsuranceRateUpdateInput): Prisma.Prisma__InsuranceRateClient<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        description: string | null;
        isDefault: boolean;
        coverageType: string | null;
        annualRate: Prisma.Decimal;
        annualRateProvider: Prisma.Decimal;
        minVehicleValue: Prisma.Decimal | null;
        maxVehicleValue: Prisma.Decimal | null;
        minTenure: number | null;
        maxTenure: number | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    deleteInsurance(id: string): Prisma.Prisma__InsuranceRateClient<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        description: string | null;
        isDefault: boolean;
        coverageType: string | null;
        annualRate: Prisma.Decimal;
        annualRateProvider: Prisma.Decimal;
        minVehicleValue: Prisma.Decimal | null;
        maxVehicleValue: Prisma.Decimal | null;
        minTenure: number | null;
        maxTenure: number | null;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    listPackages(query: PaginationQueryDto): Promise<{
        total: number;
        limit: number;
        offset: number;
        items: unknown[];
    }>;
    getPackage(id: string): Promise<{}>;
    createPackage(data: Prisma.PackageCreateInput): Prisma.Prisma__PackageClient<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        items: Prisma.JsonValue;
        description: string | null;
        price: Prisma.Decimal;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    updatePackage(id: string, data: Prisma.PackageUpdateInput): Prisma.Prisma__PackageClient<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        items: Prisma.JsonValue;
        description: string | null;
        price: Prisma.Decimal;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    deletePackage(id: string): Prisma.Prisma__PackageClient<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        status: string;
        items: Prisma.JsonValue;
        description: string | null;
        price: Prisma.Decimal;
    }, never, import("@prisma/client/runtime/library").DefaultArgs, Prisma.PrismaClientOptions>;
    getSettings(): Promise<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        isActive: boolean;
        priority: number;
        description: string | null;
        principalDiscountEnabled: boolean;
        principalDiscountType: string;
        principalDiscountValue: Prisma.Decimal;
        principalDiscountMinAmount: Prisma.Decimal;
        interestDiscountEnabled: boolean;
        interestDiscountType: string;
        interestDiscountValue: Prisma.Decimal;
        interestDiscountMinAmount: Prisma.Decimal;
        minSettlementAmount: Prisma.Decimal;
        minRemainingPayments: number;
        maxDiscountAmount: Prisma.Decimal | null;
        maxDiscountPercentage: Prisma.Decimal | null;
        tieredDiscounts: Prisma.JsonValue;
        validFrom: Date | null;
        validUntil: Date | null;
    }>;
    patchSettings(data: Prisma.SettlementDiscountSettingsUpdateInput): Promise<{
        name: string;
        id: string;
        createdAt: Date;
        updatedAt: Date;
        isActive: boolean;
        priority: number;
        description: string | null;
        principalDiscountEnabled: boolean;
        principalDiscountType: string;
        principalDiscountValue: Prisma.Decimal;
        principalDiscountMinAmount: Prisma.Decimal;
        interestDiscountEnabled: boolean;
        interestDiscountType: string;
        interestDiscountValue: Prisma.Decimal;
        interestDiscountMinAmount: Prisma.Decimal;
        minSettlementAmount: Prisma.Decimal;
        minRemainingPayments: number;
        maxDiscountAmount: Prisma.Decimal | null;
        maxDiscountPercentage: Prisma.Decimal | null;
        tieredDiscounts: Prisma.JsonValue;
        validFrom: Date | null;
        validUntil: Date | null;
    }>;
    private paged;
    private one;
}
