/** DriveMarket brand tokens — see docs/drivemarket/11_DESIGN_GUIDELINES.md */
export const brandTokens = {
  graphite980: '#0B1215',
  graphite900: '#121A1E',
  graphite800: '#1C282E',
  graphite700: '#2A3A42',
  ink: '#142027',
  slate600: '#5A6B73',
  slate400: '#8A9AA2',
  slate200: '#D5DEE3',
  canvas: '#EEF2F4',
  surface: '#FFFFFF',
  surfaceMuted: '#F5F8F9',
  amber: '#E6A100',
  amberDeep: '#B87B00',
  steel: '#2F6F8F',
  steelSoft: '#E3EEF4',
  success: '#1B7F5A',
  successSoft: '#E6F5EF',
  warning: '#C47A00',
  warningSoft: '#FFF4E0',
  danger: '#B42318',
  dangerSoft: '#FCEBEA',
} as const;

export const brandMeta = {
  name: 'DriveMarket',
  tagline: 'Cars you can finance. Clearly.',
  direction: 'Editorial Automotive Marketplace',
  logo: {
    wordmarkOnDark: '/brand/dm-wordmark-light.svg',
    wordmarkOnLight: '/brand/dm-wordmark-dark.svg',
    mark: '/brand/dm-mark.svg',
  },
} as const;

export const cssVarNames = {
  graphite980: '--dm-graphite-980',
  graphite900: '--dm-graphite-900',
  graphite800: '--dm-graphite-800',
  graphite700: '--dm-graphite-700',
  ink: '--dm-ink',
  slate600: '--dm-slate-600',
  slate400: '--dm-slate-400',
  slate200: '--dm-slate-200',
  canvas: '--dm-canvas',
  surface: '--dm-surface',
  surfaceMuted: '--dm-surface-muted',
  amber: '--dm-amber',
  amberDeep: '--dm-amber-deep',
  steel: '--dm-steel',
  steelSoft: '--dm-steel-soft',
  success: '--dm-success',
  successSoft: '--dm-success-soft',
  warning: '--dm-warning',
  warningSoft: '--dm-warning-soft',
  danger: '--dm-danger',
  dangerSoft: '--dm-danger-soft',
} as const;
