import { Prisma, User } from '@prisma/client';
import type { AuthInstance } from '../auth/auth.constants';
import { AppConfigService } from '../config/app-config.service';
import { ActivityService } from '../common/activity.service';
import { MailService } from '../mail/mail.service';
import { PrismaService } from '../prisma/prisma.service';
import type { ApplicationDocCategory } from './application-documents';
import type { InstallmentPlan } from "@drivemarket/shared/installment-plan";
import { ZohoCrmService } from '../integrations/zoho/zoho-crm.service';
import { ApplicationIntakeService } from './application-intake.service';
export type StaffCustomerSnapshot = Record<string, unknown>;
export type StaffCreateApplicationDto = {
    productId?: string;
    productIds?: string[];
    offerId: string;
    customerSnapshot: StaffCustomerSnapshot;
    pricingSnapshot: Record<string, unknown>;
    installmentPlan?: InstallmentPlan;
    agentUserId?: string;
    listPrice?: number;
    sellingPrice?: number;
    hideInterest?: boolean;
    companyId?: string;
    submit?: boolean;
};
export declare class ApplicationsStaffService {
    private readonly prisma;
    private readonly activity;
    private readonly mail;
    private readonly appConfig;
    private readonly auth;
    private readonly zoho;
    private readonly intake;
    constructor(prisma: PrismaService, activity: ActivityService, mail: MailService, appConfig: AppConfigService, auth: AuthInstance, zoho: ZohoCrmService, intake: ApplicationIntakeService);
    private audienceFor;
    private resolveBranchId;
    create(actor: User, dto: StaffCreateApplicationDto): Promise<{
        created_ids: string[];
        financing_source: string;
        finance_partner_name: string | null;
        branch_name: string | null;
        takaful_policies?: {
            id: string;
            application_id: string;
            provider: string | null;
            policy_number: string | null;
            coverage_type: string | null;
            coverage_amount: number | null;
            premium_amount: number | null;
            issued_at: string | null;
            effective_from: string | null;
            expires_at: string | null;
            days_to_expiry: number | null;
            riders: string[];
            status: string;
            declaration_accepted_at: string | null;
            declaration_version: string | null;
            has_document: boolean;
            verified_at: string | null;
            created_at: string;
        }[] | undefined;
        payment_schedules?: {
            id: string;
            sequence: number;
            due_date: Date;
            amount: number | null;
            paid_amount: number | null;
            remaining_amount: number | null;
            status: string;
            paid_at: Date | null;
            pending_waive_reason: string | null;
            pending_waive_requested_by_id: string | null;
        }[] | undefined;
        offer?: {
            is_default?: boolean | undefined;
            id: string;
            name: string;
            annual_rent_rate: number | null;
            tenure_options: Prisma.JsonValue;
            min_down_payment_pct: number | null;
            finance_partner_id: string | null;
            finance_partner_name: string | null;
            crm_adapter: string | null;
        } | undefined;
        customer?: {
            name: string | null;
            email: string;
            phone: string | null;
        } | undefined;
        company?: {
            id: string;
            name: string;
        } | undefined;
        documents?: {
            id: string;
            category: string;
            mime_type: string | null;
            created_at: Date;
            original_name: string | null;
            kyc_document_type: string | null;
            verification_status: string | null;
        }[] | undefined;
        product?: {
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: string | null;
            engine: string | null;
            transmission: string | null;
            cylinders: number | null;
            drivetrain: string | null;
            body_type: string | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number | null;
            finance_eligible: boolean | null;
            warranty_months: number | null;
            warranty_notes: string | null;
            listing_status: string | null;
            company_id: string | null;
            published_at: Date | null;
            default_offer_id: string | null;
        } | undefined;
    }>;
    submitDraft(actor: User, id: string): Promise<{
        financing_source: string;
        finance_partner_name: string | null;
        branch_name: string | null;
        takaful_policies?: {
            id: string;
            application_id: string;
            provider: string | null;
            policy_number: string | null;
            coverage_type: string | null;
            coverage_amount: number | null;
            premium_amount: number | null;
            issued_at: string | null;
            effective_from: string | null;
            expires_at: string | null;
            days_to_expiry: number | null;
            riders: string[];
            status: string;
            declaration_accepted_at: string | null;
            declaration_version: string | null;
            has_document: boolean;
            verified_at: string | null;
            created_at: string;
        }[] | undefined;
        payment_schedules?: {
            id: string;
            sequence: number;
            due_date: Date;
            amount: number | null;
            paid_amount: number | null;
            remaining_amount: number | null;
            status: string;
            paid_at: Date | null;
            pending_waive_reason: string | null;
            pending_waive_requested_by_id: string | null;
        }[] | undefined;
        offer?: {
            is_default?: boolean | undefined;
            id: string;
            name: string;
            annual_rent_rate: number | null;
            tenure_options: Prisma.JsonValue;
            min_down_payment_pct: number | null;
            finance_partner_id: string | null;
            finance_partner_name: string | null;
            crm_adapter: string | null;
        } | undefined;
        customer?: {
            name: string | null;
            email: string;
            phone: string | null;
        } | undefined;
        company?: {
            id: string;
            name: string;
        } | undefined;
        documents?: {
            id: string;
            category: string;
            mime_type: string | null;
            created_at: Date;
            original_name: string | null;
            kyc_document_type: string | null;
            verification_status: string | null;
        }[] | undefined;
        product?: {
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: string | null;
            engine: string | null;
            transmission: string | null;
            cylinders: number | null;
            drivetrain: string | null;
            body_type: string | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number | null;
            finance_eligible: boolean | null;
            warranty_months: number | null;
            warranty_notes: string | null;
            listing_status: string | null;
            company_id: string | null;
            published_at: Date | null;
            default_offer_id: string | null;
        } | undefined;
    }>;
    uploadDoc(actor: User, id: string, category: ApplicationDocCategory, file: Express.Multer.File, storage: {
        assertKycFile: (f: Express.Multer.File) => void;
        uploadKyc: (f: Express.Multer.File, appId: string, cat: string) => Promise<string>;
    }): Promise<{
        id: string;
        category: import(".prisma/client").$Enums.DocumentCategory;
        mime_type: string | null;
        created_at: Date;
    }>;
    private findOrCreateWalkInCustomer;
}
