import { ConfigService } from '@nestjs/config';
import { ApplicationStatus, Prisma, User } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { ActivityService } from '../common/activity.service';
import { AnalyticsService } from '../analytics/analytics.service';
import { ComplianceService } from '../compliance/compliance.service';
import { StorageService } from '../storage/storage.service';
export declare class ApplicationsLifecycleService {
    private readonly prisma;
    private readonly activity;
    private readonly analytics;
    private readonly storage;
    private readonly compliance;
    private readonly config;
    constructor(prisma: PrismaService, activity: ActivityService, analytics: AnalyticsService, storage: StorageService, compliance: ComplianceService, config: ConfigService);
    private assertOps;
    private assertDecisionRole;
    private assertDownPaymentRole;
    private evaluateCreditApproval;
    private logCreditDecision;
    approveWithContract(user: User, id: string, opts?: {
        overrideReason?: string | null;
    }): Promise<{
        financing_source: string;
        finance_partner_name: string | null;
        branch_name: string | null;
        takaful_policies?: {
            id: string;
            application_id: string;
            provider: string | null;
            policy_number: string | null;
            coverage_type: string | null;
            coverage_amount: number | null;
            premium_amount: number | null;
            issued_at: string | null;
            effective_from: string | null;
            expires_at: string | null;
            days_to_expiry: number | null;
            riders: string[];
            status: string;
            declaration_accepted_at: string | null;
            declaration_version: string | null;
            has_document: boolean;
            verified_at: string | null;
            created_at: string;
        }[] | undefined;
        payment_schedules?: {
            id: string;
            sequence: number;
            due_date: Date;
            amount: number | null;
            paid_amount: number | null;
            remaining_amount: number | null;
            status: string;
            paid_at: Date | null;
            pending_waive_reason: string | null;
            pending_waive_requested_by_id: string | null;
        }[] | undefined;
        offer?: {
            is_default?: boolean | undefined;
            id: string;
            name: string;
            annual_rent_rate: number | null;
            tenure_options: Prisma.JsonValue;
            min_down_payment_pct: number | null;
            finance_partner_id: string | null;
            finance_partner_name: string | null;
            crm_adapter: string | null;
        } | undefined;
        customer?: {
            name: string | null;
            email: string;
            phone: string | null;
        } | undefined;
        company?: {
            id: string;
            name: string;
        } | undefined;
        documents?: {
            id: string;
            category: string;
            mime_type: string | null;
            created_at: Date;
            original_name: string | null;
            kyc_document_type: string | null;
            verification_status: string | null;
        }[] | undefined;
        product?: {
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: string | null;
            engine: string | null;
            transmission: string | null;
            cylinders: number | null;
            drivetrain: string | null;
            body_type: string | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number | null;
            finance_eligible: boolean | null;
            warranty_months: number | null;
            warranty_notes: string | null;
            listing_status: string | null;
            company_id: string | null;
            published_at: Date | null;
            default_offer_id: string | null;
        } | undefined;
    }>;
    downloadContract(user: User, id: string): Promise<{
        filename: string;
        buffer: Buffer;
        contentType: string;
    }>;
    private assertSignedContractMatchesGenerated;
    submitSignedContract(user: User, id: string, file: Express.Multer.File): Promise<{
        financing_source: string;
        finance_partner_name: string | null;
        branch_name: string | null;
        takaful_policies?: {
            id: string;
            application_id: string;
            provider: string | null;
            policy_number: string | null;
            coverage_type: string | null;
            coverage_amount: number | null;
            premium_amount: number | null;
            issued_at: string | null;
            effective_from: string | null;
            expires_at: string | null;
            days_to_expiry: number | null;
            riders: string[];
            status: string;
            declaration_accepted_at: string | null;
            declaration_version: string | null;
            has_document: boolean;
            verified_at: string | null;
            created_at: string;
        }[] | undefined;
        payment_schedules?: {
            id: string;
            sequence: number;
            due_date: Date;
            amount: number | null;
            paid_amount: number | null;
            remaining_amount: number | null;
            status: string;
            paid_at: Date | null;
            pending_waive_reason: string | null;
            pending_waive_requested_by_id: string | null;
        }[] | undefined;
        offer?: {
            is_default?: boolean | undefined;
            id: string;
            name: string;
            annual_rent_rate: number | null;
            tenure_options: Prisma.JsonValue;
            min_down_payment_pct: number | null;
            finance_partner_id: string | null;
            finance_partner_name: string | null;
            crm_adapter: string | null;
        } | undefined;
        customer?: {
            name: string | null;
            email: string;
            phone: string | null;
        } | undefined;
        company?: {
            id: string;
            name: string;
        } | undefined;
        documents?: {
            id: string;
            category: string;
            mime_type: string | null;
            created_at: Date;
            original_name: string | null;
            kyc_document_type: string | null;
            verification_status: string | null;
        }[] | undefined;
        product?: {
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: string | null;
            engine: string | null;
            transmission: string | null;
            cylinders: number | null;
            drivetrain: string | null;
            body_type: string | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number | null;
            finance_eligible: boolean | null;
            warranty_months: number | null;
            warranty_notes: string | null;
            listing_status: string | null;
            company_id: string | null;
            published_at: Date | null;
            default_offer_id: string | null;
        } | undefined;
    }>;
    submitSignedContractOps(user: User, id: string, file: Express.Multer.File): Promise<{
        financing_source: string;
        finance_partner_name: string | null;
        branch_name: string | null;
        takaful_policies?: {
            id: string;
            application_id: string;
            provider: string | null;
            policy_number: string | null;
            coverage_type: string | null;
            coverage_amount: number | null;
            premium_amount: number | null;
            issued_at: string | null;
            effective_from: string | null;
            expires_at: string | null;
            days_to_expiry: number | null;
            riders: string[];
            status: string;
            declaration_accepted_at: string | null;
            declaration_version: string | null;
            has_document: boolean;
            verified_at: string | null;
            created_at: string;
        }[] | undefined;
        payment_schedules?: {
            id: string;
            sequence: number;
            due_date: Date;
            amount: number | null;
            paid_amount: number | null;
            remaining_amount: number | null;
            status: string;
            paid_at: Date | null;
            pending_waive_reason: string | null;
            pending_waive_requested_by_id: string | null;
        }[] | undefined;
        offer?: {
            is_default?: boolean | undefined;
            id: string;
            name: string;
            annual_rent_rate: number | null;
            tenure_options: Prisma.JsonValue;
            min_down_payment_pct: number | null;
            finance_partner_id: string | null;
            finance_partner_name: string | null;
            crm_adapter: string | null;
        } | undefined;
        customer?: {
            name: string | null;
            email: string;
            phone: string | null;
        } | undefined;
        company?: {
            id: string;
            name: string;
        } | undefined;
        documents?: {
            id: string;
            category: string;
            mime_type: string | null;
            created_at: Date;
            original_name: string | null;
            kyc_document_type: string | null;
            verification_status: string | null;
        }[] | undefined;
        product?: {
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: string | null;
            engine: string | null;
            transmission: string | null;
            cylinders: number | null;
            drivetrain: string | null;
            body_type: string | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number | null;
            finance_eligible: boolean | null;
            warranty_months: number | null;
            warranty_notes: string | null;
            listing_status: string | null;
            company_id: string | null;
            published_at: Date | null;
            default_offer_id: string | null;
        } | undefined;
    }>;
    opsTransition(user: User, id: string, toStatus: ApplicationStatus, reason?: string, overrideReason?: string | null): Promise<{
        financing_source: string;
        finance_partner_name: string | null;
        branch_name: string | null;
        takaful_policies?: {
            id: string;
            application_id: string;
            provider: string | null;
            policy_number: string | null;
            coverage_type: string | null;
            coverage_amount: number | null;
            premium_amount: number | null;
            issued_at: string | null;
            effective_from: string | null;
            expires_at: string | null;
            days_to_expiry: number | null;
            riders: string[];
            status: string;
            declaration_accepted_at: string | null;
            declaration_version: string | null;
            has_document: boolean;
            verified_at: string | null;
            created_at: string;
        }[] | undefined;
        payment_schedules?: {
            id: string;
            sequence: number;
            due_date: Date;
            amount: number | null;
            paid_amount: number | null;
            remaining_amount: number | null;
            status: string;
            paid_at: Date | null;
            pending_waive_reason: string | null;
            pending_waive_requested_by_id: string | null;
        }[] | undefined;
        offer?: {
            is_default?: boolean | undefined;
            id: string;
            name: string;
            annual_rent_rate: number | null;
            tenure_options: Prisma.JsonValue;
            min_down_payment_pct: number | null;
            finance_partner_id: string | null;
            finance_partner_name: string | null;
            crm_adapter: string | null;
        } | undefined;
        customer?: {
            name: string | null;
            email: string;
            phone: string | null;
        } | undefined;
        company?: {
            id: string;
            name: string;
        } | undefined;
        documents?: {
            id: string;
            category: string;
            mime_type: string | null;
            created_at: Date;
            original_name: string | null;
            kyc_document_type: string | null;
            verification_status: string | null;
        }[] | undefined;
        product?: {
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: string | null;
            engine: string | null;
            transmission: string | null;
            cylinders: number | null;
            drivetrain: string | null;
            body_type: string | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number | null;
            finance_eligible: boolean | null;
            warranty_months: number | null;
            warranty_notes: string | null;
            listing_status: string | null;
            company_id: string | null;
            published_at: Date | null;
            default_offer_id: string | null;
        } | undefined;
    }>;
    recordDownPayment(user: User, id: string, body: {
        amount: number;
        method?: string;
        reference?: string;
        paidAt?: string;
    }): Promise<{
        financing_source: string;
        finance_partner_name: string | null;
        branch_name: string | null;
        takaful_policies?: {
            id: string;
            application_id: string;
            provider: string | null;
            policy_number: string | null;
            coverage_type: string | null;
            coverage_amount: number | null;
            premium_amount: number | null;
            issued_at: string | null;
            effective_from: string | null;
            expires_at: string | null;
            days_to_expiry: number | null;
            riders: string[];
            status: string;
            declaration_accepted_at: string | null;
            declaration_version: string | null;
            has_document: boolean;
            verified_at: string | null;
            created_at: string;
        }[] | undefined;
        payment_schedules?: {
            id: string;
            sequence: number;
            due_date: Date;
            amount: number | null;
            paid_amount: number | null;
            remaining_amount: number | null;
            status: string;
            paid_at: Date | null;
            pending_waive_reason: string | null;
            pending_waive_requested_by_id: string | null;
        }[] | undefined;
        offer?: {
            is_default?: boolean | undefined;
            id: string;
            name: string;
            annual_rent_rate: number | null;
            tenure_options: Prisma.JsonValue;
            min_down_payment_pct: number | null;
            finance_partner_id: string | null;
            finance_partner_name: string | null;
            crm_adapter: string | null;
        } | undefined;
        customer?: {
            name: string | null;
            email: string;
            phone: string | null;
        } | undefined;
        company?: {
            id: string;
            name: string;
        } | undefined;
        documents?: {
            id: string;
            category: string;
            mime_type: string | null;
            created_at: Date;
            original_name: string | null;
            kyc_document_type: string | null;
            verification_status: string | null;
        }[] | undefined;
        product?: {
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: string | null;
            engine: string | null;
            transmission: string | null;
            cylinders: number | null;
            drivetrain: string | null;
            body_type: string | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number | null;
            finance_eligible: boolean | null;
            warranty_months: number | null;
            warranty_notes: string | null;
            listing_status: string | null;
            company_id: string | null;
            published_at: Date | null;
            default_offer_id: string | null;
        } | undefined;
    }>;
    activate(user: User, id: string, opts?: {
        direct?: boolean;
        overrideReason?: string | null;
    }): Promise<{
        financing_source: string;
        finance_partner_name: string | null;
        branch_name: string | null;
        takaful_policies?: {
            id: string;
            application_id: string;
            provider: string | null;
            policy_number: string | null;
            coverage_type: string | null;
            coverage_amount: number | null;
            premium_amount: number | null;
            issued_at: string | null;
            effective_from: string | null;
            expires_at: string | null;
            days_to_expiry: number | null;
            riders: string[];
            status: string;
            declaration_accepted_at: string | null;
            declaration_version: string | null;
            has_document: boolean;
            verified_at: string | null;
            created_at: string;
        }[] | undefined;
        payment_schedules?: {
            id: string;
            sequence: number;
            due_date: Date;
            amount: number | null;
            paid_amount: number | null;
            remaining_amount: number | null;
            status: string;
            paid_at: Date | null;
            pending_waive_reason: string | null;
            pending_waive_requested_by_id: string | null;
        }[] | undefined;
        offer?: {
            is_default?: boolean | undefined;
            id: string;
            name: string;
            annual_rent_rate: number | null;
            tenure_options: Prisma.JsonValue;
            min_down_payment_pct: number | null;
            finance_partner_id: string | null;
            finance_partner_name: string | null;
            crm_adapter: string | null;
        } | undefined;
        customer?: {
            name: string | null;
            email: string;
            phone: string | null;
        } | undefined;
        company?: {
            id: string;
            name: string;
        } | undefined;
        documents?: {
            id: string;
            category: string;
            mime_type: string | null;
            created_at: Date;
            original_name: string | null;
            kyc_document_type: string | null;
            verification_status: string | null;
        }[] | undefined;
        product?: {
            id: string;
            slug: string;
            make: string;
            model: string;
            trim: string | null;
            model_year: number;
            condition: string | null;
            engine: string | null;
            transmission: string | null;
            cylinders: number | null;
            drivetrain: string | null;
            body_type: string | null;
            color: string | null;
            mileage: number | null;
            description: string | null;
            price: number | null;
            finance_eligible: boolean | null;
            warranty_months: number | null;
            warranty_notes: string | null;
            listing_status: string | null;
            company_id: string | null;
            published_at: Date | null;
            default_offer_id: string | null;
        } | undefined;
    }>;
    private unreserveIfNeeded;
}
