import { type ParsedQid, type ResidencyClass } from "@drivemarket/shared/domain-rules";
export declare const GENDER_VALUES: readonly ["male", "female", "prefer_not_to_say"];
export type GenderValue = (typeof GENDER_VALUES)[number];
export declare const APPLICANT_TYPES: readonly ["individual", "corporate"];
export type ApplicantType = (typeof APPLICANT_TYPES)[number];
export declare const RESIDENCY_VALUES: readonly ["qatari", "expat"];
export declare const GUARANTOR_RELATIONSHIPS: readonly ["spouse", "parent", "sibling", "other"];
export type GuarantorRelationship = (typeof GUARANTOR_RELATIONSHIPS)[number];
export declare const RESIDENCE_DURATION_VALUES: readonly string[];
export type CustomerEmployment = {
    company?: string;
    jobTitle?: string;
    position?: string;
    employmentType?: string;
    employmentDuration?: string;
    salary?: number;
};
export type CustomerGuarantor = {
    fullName?: string;
    qid?: string;
    phone?: string;
    relationship?: string;
    monthlyIncome?: number;
};
export type CustomerSnapshot = {
    full_name: string;
    phone: string;
    qid: string;
    email?: string;
    applicantType: ApplicantType;
    firstName?: string;
    lastName?: string;
    gender?: GenderValue;
    dateOfBirth?: string;
    nationality?: string;
    residency?: ResidencyClass;
    residenceDuration?: string;
    city?: string;
    address?: Record<string, unknown>;
    employment?: string | CustomerEmployment;
    income?: number;
    monthlyIncome?: number;
    monthlyLiabilities?: number;
    hasGuarantor?: boolean;
    guarantor?: CustomerGuarantor;
    corporate?: Record<string, unknown>;
    [key: string]: unknown;
};
export type CustomerSnapshotInput = Record<string, unknown>;
export type CustomerProfileFields = {
    firstName?: string;
    lastName?: string;
    gender?: GenderValue;
    dateOfBirth?: Date;
    nationality?: string;
};
export type NormalizedCustomerSnapshot = {
    snapshot: CustomerSnapshot;
    parsedQid: ParsedQid;
    residency: ResidencyClass | null;
    birthYear: number | null;
    profile: CustomerProfileFields;
};
export declare function isoDateOnly(value: unknown): string | null;
export declare function readCustomerSnapshot(raw: unknown): CustomerSnapshot;
export declare function employmentTypeOf(snapshot: CustomerSnapshotInput | null | undefined): string | null;
export declare function hasGuarantorOf(snapshot: CustomerSnapshotInput | null | undefined): boolean;
export declare function residencyOf(snapshot: CustomerSnapshotInput | null | undefined): ResidencyClass | null;
export declare function birthYearOf(snapshot: CustomerSnapshotInput | null | undefined): number | null;
export declare function normalizePersonName(name: string | null | undefined): string;
export declare function normalizeCustomerSnapshot(input: CustomerSnapshotInput, opts?: {
    now?: Date;
    requireContact?: boolean;
}): NormalizedCustomerSnapshot;
