import fs from 'node:fs';
import path from 'node:path';
import PizZip from 'pizzip';
import type { ContractDocumentAudience } from './template-catalog';

const LOGO_MEDIA = 'word/media/blox-logo-nav.png';
const REFERENCE_HEADER = 'BLX-TPL-011_Ijarah_Agreement.docx';

/** Logo width ~1.45in, height ~0.43in at 96dpi nav aspect. */
const LOGO_CX = 1320800;
const LOGO_CY = 392430;

export const TEMPLATE_BRAND_META: Record<string, { code: string; audience: ContractDocumentAudience }> = {
  'BLX-TPL-011_Ijarah_Agreement.docx': { code: 'BLX-TPL-011', audience: 'customer' },
  'Blox_Diminishing_Musharakah_Agreement_V2.docx': { code: 'BLX-TPL-MUSH-V2', audience: 'customer' },
  'BLX-TPL-020_Schedule_of_Ownership_and_Rental.docx': { code: 'BLX-TPL-020', audience: 'customer' },
  'BLX-TPL-004_Credit_Appraisal_Memorandum_INTERNAL.docx': { code: 'BLX-TPL-004', audience: 'ops' },
};

const BODY_REPLACEMENTS: Array<[string, string]> = [
  ['Draft for M2P implementation', 'Final'],
  ['Acceptance test for the M2P ', 'Generated by BloX · '],
  ['اختبار قبول لمحرك الاحتساب لدى M2P', 'صادر عن BloX ·'],
  [
    'DRAFT — FOR LEGAL AND SHARIAH REVIEW BEFORE USE',
    '',
  ],
  [
    'مسودة — للمراجعة القانونية والشرعية قبل الاستخدام',
    '',
  ],
];

const FOOTER_REPLACEMENTS: Array<[string, string]> = [
  ['issued to M2P Solutions Ltd', 'blox-it.com · Own it, don\'t owe it.'],
  ['BloX LLC template pack — issued to M2P Solutions Ltd', 'BloX LLC · blox-it.com · Own it, don\'t owe it.'],
  [' · v1.1 ·  | BloX |  LLC template pack — issued to M2P Solutions Ltd', ' · BloX LLC · blox-it.com · Own it, don\'t owe it.'],
  [' · v1.1 · BloX LLC template pack — issued to M2P Solutions Ltd', ' · BloX LLC · blox-it.com · Own it, don\'t owe it.'],
];

function normalizeZipPath(entry: string): string {
  return entry.replace(/\\/g, '/');
}

function zipEntryKeys(zip: PizZip): string[] {
  return Object.keys(zip.files);
}

function findZipEntry(zip: PizZip, suffix: string): string | undefined {
  const normalized = suffix.replace(/\\/g, '/');
  return zipEntryKeys(zip).find((key) => normalizeZipPath(key).endsWith(normalized));
}

function readZipText(zip: PizZip, suffix: string): string | null {
  const key = findZipEntry(zip, suffix);
  if (!key) return null;
  return zip.file(key)?.asText() ?? null;
}

function writeZipText(zip: PizZip, suffix: string, content: string): void {
  const key = findZipEntry(zip, suffix) ?? suffix.replace(/\//g, '\\');
  zip.file(key, content);
}

export function resolveBrandAssetsDir(): string {
  const candidates = [
    path.join(__dirname, 'brand'),
    path.join(__dirname, '..', '..', '..', 'assets', 'contract-brand'),
    path.join(process.cwd(), 'src', 'applications', 'documents', 'brand'),
    path.join(process.cwd(), 'assets', 'contract-brand'),
    path.join(process.cwd(), 'dist', 'applications', 'documents', 'brand'),
    path.join(process.cwd(), 'packages', 'api', 'src', 'applications', 'documents', 'brand'),
    path.join(process.cwd(), 'packages', 'api', 'assets', 'contract-brand'),
    path.join(process.cwd(), 'packages', 'api', 'dist', 'applications', 'documents', 'brand'),
  ];
  return candidates.find((dir) => fs.existsSync(path.join(dir, 'blox-logo-nav.png'))) ?? candidates[0];
}

function readLogoBuffer(): Buffer {
  const logoPath = path.join(resolveBrandAssetsDir(), 'blox-logo-nav.png');
  if (!fs.existsSync(logoPath)) {
    throw new Error('contract_brand_logo_missing');
  }
  return fs.readFileSync(logoPath);
}

function replaceAcrossXml(xml: string, pairs: Array<[string, string]>): string {
  let out = xml;
  for (const [from, to] of pairs) {
    out = out.split(from).join(to);
  }
  return out;
}

function footerLineFor(code: string, audience: ContractDocumentAudience): string {
  if (audience === 'ops') {
    return `${code} · BloX LLC · INTERNAL · CONFIDENTIAL · blox-it.com`;
  }
  return `${code} · BloX LLC · blox-it.com · Own it, don't owe it.`;
}

function patchFooterXml(xml: string, code: string, audience: ContractDocumentAudience): string {
  let out = replaceAcrossXml(xml, FOOTER_REPLACEMENTS);
  const footerText = footerLineFor(code, audience);

  const pageParagraph = /<w:p[^>]*>[\s\S]*?<w:instrText>PAGE<\/w:instrText>[\s\S]*?<\/w:p>/;
  if (pageParagraph.test(out)) {
    out = out.replace(pageParagraph, (match) => {
      const pageSection = match.match(/<w:tab\/>[\s\S]*$/)?.[0] ?? '';
      return `<w:p w14:paraId="BLOXFOOT01" w14:textId="77777777" w:rsidR="00175AB8" w:rsidRDefault="00000000"><w:pPr><w:tabs><w:tab w:val="right" w:pos="9906"/></w:tabs></w:pPr><w:r><w:rPr><w:color w:val="708090"/><w:sz w:val="13"/><w:szCs w:val="13"/></w:rPr><w:t xml:space="preserve">${footerText}</w:t></w:r>${pageSection}`;
    });
    return out;
  }

  out = out.replace(/BLX-TPL-\d+[^<]*/g, footerText);
  out = out.replace(/BLX-TPL-MUSH-V2[^<]*/g, footerText);
  out = out.replace(/Blox · Doha, Qatar · blox-it\.com\s*\|\s*Page\s*\|\s*1/g, footerText);
  return out;
}

function ensurePngContentType(zip: PizZip): void {
  const key = findZipEntry(zip, '[Content_Types].xml');
  if (!key) return;
  let xml = zip.file(key)!.asText();
  if (!xml.includes('Extension="png"')) {
    xml = xml.replace(
      '</Types>',
      '<Default Extension="png" ContentType="image/png"/></Types>',
    );
    zip.file(key, xml);
  }
}

function headerRelsPath(headerPath: string): string {
  const normalized = normalizeZipPath(headerPath);
  const fileName = path.posix.basename(normalized);
  return normalizeZipPath(path.posix.join('word', '_rels', `${fileName}.rels`));
}

function ensureHeaderImageRel(zip: PizZip, headerPath: string, relId = 'rIdLogo'): void {
  const relPath = headerRelsPath(headerPath);
  const relKey = findZipEntry(zip, relPath) ?? relPath.replace(/\//g, '\\');
  const relXml = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="${relId}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/image" Target="media/blox-logo-nav.png"/>
</Relationships>`;
  zip.file(relKey, relXml);
}

function logoDrawingRun(relId = 'rIdLogo'): string {
  return `<w:r><w:drawing><wp:inline distT="0" distB="0" distL="0" distR="0" xmlns:wp="http://schemas.openxmlformats.org/drawingml/2006/wordprocessingDrawing"><wp:extent cx="${LOGO_CX}" cy="${LOGO_CY}"/><wp:effectExtent l="0" t="0" r="0" b="0"/><wp:docPr id="100001" name="BloX Logo"/><wp:cNvGraphicFramePr><a:graphicFrameLocks xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" noChangeAspect="1"/></wp:cNvGraphicFramePr><a:graphic xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main"><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:pic xmlns:pic="http://schemas.openxmlformats.org/drawingml/2006/picture"><pic:nvPicPr><pic:cNvPr id="100001" name="BloX Logo"/><pic:cNvPicPr/></pic:nvPicPr><pic:blipFill><a:blip xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" r:embed="${relId}"/><a:stretch><a:fillRect/></a:stretch></pic:blipFill><pic:spPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="${LOGO_CX}" cy="${LOGO_CY}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom></pic:spPr></pic:pic></a:graphicData></a:graphic></wp:inline></w:drawing></w:r>`;
}

function injectLogoIntoHeaderXml(headerXml: string, relId = 'rIdLogo'): string {
  if (!headerXml.includes('<w:hdr')) return headerXml;
  if (headerXml.includes('<w:drawing>') && headerXml.includes('BloX Logo')) {
    return headerXml;
  }
  const logoParagraph =
    `<w:p w14:paraId="BLOXLOGO01" w14:textId="77777777" w:rsidR="00000000" w:rsidRDefault="00000000">${logoDrawingRun(relId)}</w:p>`;
  const bloxParagraph =
    /<w:p[^>]*>[\s\S]*?<w:t(?:\s+xml:space="preserve")?>BloX<\/w:t>[\s\S]*?<\/w:p>/;
  if (bloxParagraph.test(headerXml)) {
    return headerXml.replace(bloxParagraph, logoParagraph);
  }
  const firstCell = /<w:tc>([\s\S]*?)<\/w:tc>/;
  if (firstCell.test(headerXml)) {
    return headerXml.replace(firstCell, (match, inner) => {
      if (inner.includes('<w:drawing>')) return match;
      return `<w:tc>${logoParagraph}${inner}</w:tc>`;
    });
  }
  return headerXml;
}

function injectLogo(zip: PizZip, logo: Buffer): void {
  const mediaKey = findZipEntry(zip, LOGO_MEDIA) ?? LOGO_MEDIA.replace(/\//g, '\\');
  zip.file(mediaKey, logo);
  ensurePngContentType(zip);

  for (const suffix of ['word/header1.xml', 'word/header2.xml']) {
    const headerPath = findZipEntry(zip, suffix);
    if (!headerPath) continue;
    const xml = zip.file(headerPath)!.asText();
    if (!xml.includes('<w:hdr')) continue;
    if (xml.includes('<w:drawing>') && xml.includes('BloX Logo')) continue;
    ensureHeaderImageRel(zip, headerPath);
    writeZipText(zip, suffix, injectLogoIntoHeaderXml(xml));
  }
}

function copyZipEntry(sourceZip: PizZip, targetZip: PizZip, suffix: string): void {
  const sourceKey = findZipEntry(sourceZip, suffix);
  if (!sourceKey) return;
  const content = sourceZip.file(sourceKey);
  if (!content) return;
  const targetKey = findZipEntry(targetZip, suffix) ?? suffix.replace(/\//g, '\\');
  targetZip.file(targetKey, content.asText());
}

function copyReferenceBrandedHeader(targetZip: PizZip, templatesDir: string): void {
  const refPath = path.join(templatesDir, REFERENCE_HEADER);
  if (!fs.existsSync(refPath)) return;
  const refZip = new PizZip(fs.readFileSync(refPath));
  const refHeader = readZipText(refZip, 'word/header1.xml');
  if (!refHeader?.includes('<w:hdr')) return;

  copyZipEntry(refZip, targetZip, 'word/header1.xml');
  copyZipEntry(refZip, targetZip, 'word/_rels/header1.xml.rels');
  copyZipEntry(refZip, targetZip, 'word/footer1.xml');
  copyZipEntry(refZip, targetZip, 'word/_rels/footer1.xml.rels');
}

export function applyBranding(
  docx: Buffer,
  input: { templateFile: string; audience?: ContractDocumentAudience },
): Buffer {
  const meta = TEMPLATE_BRAND_META[input.templateFile];
  if (!meta) return docx;

  const audience = input.audience ?? meta.audience;
  const zip = new PizZip(docx);
  const templatesDir = path.join(resolveBrandAssetsDir(), '..', 'templates');

  if (input.templateFile.includes('Musharakah')) {
    copyReferenceBrandedHeader(zip, templatesDir);
  }

  const xmlTargets = [
    'word/document.xml',
    'word/header1.xml',
    'word/header2.xml',
    'word/footer1.xml',
    'word/footer2.xml',
  ];

  for (const suffix of xmlTargets) {
    const xml = readZipText(zip, suffix);
    if (!xml?.trim()) continue;
    let next = replaceAcrossXml(xml, BODY_REPLACEMENTS);
    if (suffix.includes('footer')) {
      next = patchFooterXml(next, meta.code, audience);
    }
    writeZipText(zip, suffix, next);
  }

  try {
    injectLogo(zip, readLogoBuffer());
  } catch {
    // Logo asset optional at runtime; text header remains.
  }

  for (const suffix of ['word/footer1.xml', 'word/footer2.xml']) {
    const xml = readZipText(zip, suffix);
    if (!xml?.trim()) continue;
    writeZipText(zip, suffix, patchFooterXml(xml, meta.code, audience));
  }

  return zip.generate({ type: 'nodebuffer' }) as Buffer;
}
